sentry:
    dsn: "https://21e8eb3ed8b948e4a200072629b575ce@o1270126.ingest.sentry.io/6460620"
    options:
        # Specify a fixed sample rate:
        traces_sample_rate: 1.0
        # Or provide a custom sampler:
        traces_sampler: 'sentry.callback.traces_sampler'

# Only needed when using the `traces_sampler`
services:
    sentry.callback.traces_sampler:
        class: 'App\Service\Sentry'
        factory: [ '@App\Service\Sentry', 'getTracesSampler' ]